version: 1.2
workflows:
 - name: Titan_ClearLabs
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_titan_clearlabs.wdl
   testParameterFiles:
    - empty.json
 - name: Titan_ONT
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_titan_ont.wdl
   testParameterFiles:
    - empty.json
 - name: Titan_Illumina_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_titan_illumina_pe.wdl
   testParameterFiles:
    - empty.json
 - name: Titan_Illumina_SE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_titan_illumina_se.wdl
   testParameterFiles:
    - empty.json
 - name: Mercury_PE_Prep
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mercury_pe_prep.wdl
   testParameterFiles:
    - empty.json
 - name: Mercury_SE_Prep
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mercury_se_prep.wdl
   testParameterFiles:
    - empty.json
 - name: Mercury_Batch
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mercury_batch.wdl
   testParameterFiles:
    - empty.json
 - name: Titan_Augur_Prep
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_titan_augur_prep.wdl
   testParameterFiles:
    - empty.json
 - name: Titan_Augur_Run
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_titan_augur_run.wdl
   testParameterFiles:
    - empty.json
 - name: Pangolin_Update
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_pangolin_update.wdl
   testParameterFiles:
    - empty.json
 - name: VADR_Update
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_vadr_update.wdl
   testParameterFiles:
    - empty.json
 - name: NCBI_Scrub_SE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_ncbi_scrub_se.wdl
   testParameterFiles:
    - empty.json
 - name: NCBI_Scrub_PE
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_ncbi_scrub_pe.wdl
   testParameterFiles:
    - empty.json
 - name: Titan_FASTA
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_titan_fasta.wdl
   testParameterFiles:
    - empty.json
 - name: Titan_WWVC
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_titan_wwvc.wdl
   testParameterFiles:
    - empty.json
 - name: Freyja_FASTQ
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_freyja_fastq.wdl
   testParameterFiles:
    - empty.json
 - name: Freyja_Plot
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_freyja_plot.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_Validate
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_theiacov_validate.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_Augur_DistanceTree
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_theiacov_augur_distance_tree.wdl
   testParameterFiles:
    - empty.json
